<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <RootNamespace>ReverieWorld.DiceRoll</RootNamespace>

    <ImplicitUsings>enable</ImplicitUsings>

    <Nullable>enable</Nullable>
    <IsAotCompatible>True</IsAotCompatible>

    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>

    <GenerateDocumentationFile>True</GenerateDocumentationFile>

    <VersionPrefix>0.1.0</VersionPrefix>
    <Authors>dimson_n</Authors>
    <Company />
    <Description>Dice roller for the Border of dreams role-playing game system</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/dimson-n/ReverieWorld.DiceRoll</RepositoryUrl>
    <PackageTags>d6,dice,roll,rpg</PackageTags>

    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>

    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <InternalsVisibleTo Include="ReverieWorld.DiceRoll.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
